  # SimpleCurrencies
  # Made by CarThax08
  # https://www.github.com/carthax08/SimpleCurrencies
  # the currencies tab can be edited to your liking, but a few default values are set.
  # Keep all currencies lower case to prevent issues.

  # If you want to edit the items that can be sold as well as their values, go to prices.yml

  currencies:
    - tokens
    - money